import { Hono } from "hono";
import { logger } from "hono/logger";
import { cors } from "hono/cors";
import { HTTPException } from "hono/http-exception";
import type { ErrorResponse } from "shared";
import { apiRoutes } from "./routes/api.route";
import { prisma } from "@repo/database";
import { secureHeaders } from "hono/secure-headers";
import { rateLimiter } from "hono-rate-limiter";
import { csrf } from "hono/csrf";
import { envParsed } from "./env";
import cloudinary from "cloudinary";
import { bulkRouter } from "./routes/bulk.route";
import { verifyUserRoleAccess } from "./middlewares/auth.middleware";
import { metaService } from "./services/metaservice";
import { handleRepoError } from "./routes/lead/lead.route";
import { showRoutes } from "hono/dev";

export const app = new Hono();
const allowedOrigins = envParsed.ALLOWED_ORIGINS;
const proofOrigins = envParsed.PROOF_ORIGINS;
app.use("*", logger());
app.use(secureHeaders());
app.use(
  "*",
  cors({
    origin: allowedOrigins,
    credentials: true,
    allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"],
    allowHeaders: ["Content-Type", "Authorization", "xxx-csrf-access-token", "x-seller-id", "x-hub-signature-256"],
  }),
);

// app.use(csrf({ origin: allowedOrigins.concat(proofOrigins) }));
// Apply rate limiting middleware
app.use(
  rateLimiter({
    windowMs: 15 * 60 * 1000, // 15 minutes
    standardHeaders: true,
    limit: 100, // Limit each client to 100 requests per window
    keyGenerator: (c) => c.req.header("x-forwarded-for") ?? "", // Use IP address as key
    message: {
      message: "Too many requests, please try again later",
    },
  }),
);

export type SuccessResponse<T = undefined> = T extends undefined
  ? { success: true; message: string }
  : { success: true; message: string; data: T };

// TODO: refactor this routing
export const appRoutes = app.basePath("/api").route("/", apiRoutes);

// error handling for http errors
app.onError((err, c) => {
  if (err instanceof HTTPException) {
    console.log("Error caause:", err.cause);
    const errorResponse =
      err.res ??
      c.json<ErrorResponse>(
        {
          success: false,
          error: err.message,
          isFormError:
            err.cause && typeof err.cause === "object" && "form" in err.cause
              ? err.cause.form === true
              : false,
        },
        err.status,
      );

    // Return the error response generated by HTTPException
    return errorResponse;
  }

  // For other types of errors, return a generic error response
  return c.json<ErrorResponse>(
    {
      success: false,
      error:
        process.env.NODE_ENV === "production"
          ? "Interal Server Error"
          : (err.stack ?? err.message),
    },
    500,
  );
});

app.get("/", (c) => {
  return c.json({ status: "ok" });
});

app.get("/health", async (c) => {
  try {
    await prisma.$queryRaw`SELECT 1`;
    return c.json({ status: "ok", database: "connected" });
  } catch (error) {
    return c.json(
      { status: "error", database: "disconnected", error: String(error) },
      503,
    );
  }
});

// app.route("/upload", bulkRouter);

// app.post("/cloudinary", async (c) => {
//   const body = await c.req.parseBody();
//   const file = body["file"];

//   if (!(file instanceof File)) {
//     return c.text("File is required", 400);
//   }

//   if(!file.name.endsWith(".pdf")) {
//     return c.text("Only PDF files are allowed", 400);
//   }

//   const arrayBuffer = await file.arrayBuffer();
//   const base64 = Buffer.from(arrayBuffer).toString("base64");
//   const dataUri = `data:application/pdf;base64,${base64}`;

//   const result = await cloudinary.v2.uploader.upload(dataUri, {
//     resource_type: "raw",       // required for PDFs
//     use_filename: true,
//     filename_override: file.name,
//   });

//   return c.json(result);

// });


showRoutes(app);

export default {
  port: envParsed.PORT,
  hostname: "0.0.0.0",
  fetch: app.fetch,
};