import { Hono } from "hono";
import { logger } from "hono/logger";
import { leadRoutes } from "@/routes/lead.route";
import { cors } from "hono/cors";
import { HTTPException } from "hono/http-exception";

const app = new Hono();

app.use("*", logger());
app.use(
  "*",
  cors({
    origin: "*",
  }),
);

export type ErrorResponse = {
  success: false;
  error: string;
  isFormError?: boolean;
};

const _apiRoutes = app.basePath("/api").route("/leads", leadRoutes);

app.onError((err, c) => {
  if (err instanceof HTTPException) {
    const errorResponse =
      err.res ??
      c.json<ErrorResponse>(
        {
          success: false,
          error: err.message,
          isFormError:
            err.cause && typeof err.cause === "object" && "form" in err.cause
              ? err.cause.form === true
              : false,
        },
        err.status,
      );

    // Return the error response generated by HTTPException
    return errorResponse;
  }

  return c.json<ErrorResponse>(
    {
      success: false,
      error:
        process.env.NODE_ENV === "production"
          ? "Interal Server Error"
          : (err.stack ?? err.message),
    },
    500,
  );
});

app.get("/", (c) => {
  return c.json({ status: "ok" });
});

export default app;
export type ApiRoutes = typeof _apiRoutes;
