import { Hono } from "hono";
import { logger } from "hono/logger";
import { leadRoutes } from "@/routes/lead.route";
import { cors } from "hono/cors";
import { HTTPException } from "hono/http-exception";
import { userRoutes } from "./routes/user.route";
import { courseRoutes } from "./routes/course.route";
import { campaingRoutes } from "./routes/campaing.route";
import { productRoutes } from "./routes/product.route";
import { orderRoutes } from "./routes/order.route";
import type {ErrorResponse} from "shared"

export const app = new Hono();

app.use("*", logger());
app.use(
  "*",
  cors({
    origin: "*",
  }),
);

export type SuccessResponse<T = undefined> = T extends undefined
  ? { success: true; message: string }
  : { success: true; message: string; data: T };

// TODO: refactor this routing
export const apiRoutes = app
  .basePath("/api")
  .route("/leads", leadRoutes)
  .route("/users", userRoutes)
  .route("/courses", courseRoutes)
  .route("/campaings", campaingRoutes)
  .route("/products", productRoutes)
  .route("/orders", orderRoutes)

  // error handling for http errors
app.onError((err, c) => {
  if (err instanceof HTTPException) {
    console.log("Error caause:", err.cause);
    const errorResponse =
      err.res ??
      c.json<ErrorResponse>(
        {
          success: false,
          error: err.message,
          isFormError:
            err.cause && typeof err.cause === "object" && "form" in err.cause
              ? err.cause.form === true
              : false,
        },
        err.status,
      );

    // Return the error response generated by HTTPException
    return errorResponse;
  }

  // For other types of errors, return a generic error response
  return c.json<ErrorResponse>(
    {
      success: false,
      error:
        process.env.NODE_ENV === "production"
          ? "Interal Server Error"
          : (err.stack ?? err.message),
    },
    500,
  );
});

app.get("/", (c) => {
  return c.json({ status: "ok" });
});

export default {
  port: Number(process.env.PORT) || 3000, 
  hostname: '0.0.0.0', 
  fetch: app.fetch, 
}