import { CheckCircle2, Circle, Clock3, MessageCircle } from "lucide-react";
import { Badge } from "@/core/components/ui/badge";
import { Button } from "@/core/components/ui/button";
import { Card } from "@/core/components/ui/card";
import { Skeleton } from "@/core/components/ui/skeleton";
import type { LeadCampaignMember, LeadInteraction, LeadTask } from "./leadDetail.types";
import { displayEnum, formatLeadDate, personFullName } from "./leadDetail.formatters";
import { CampaignContextSelector } from "./CampaignContextSelector";

interface CommonProps { members: LeadCampaignMember[]; selectedMemberId: string; onChange: (memberId: string) => void; isLoading: boolean; isError: boolean; onRetry: () => void }
const EmptyCampaign = () => <p className="py-10 text-center text-muted-foreground">Este prospecto todavía no está asociado a una campaña.</p>;
const QueryError = ({ onRetry }: { onRetry: () => void }) => <div className="py-10 text-center"><p className="text-destructive">No fue posible cargar la información.</p><Button variant="outline" className="mt-3" onClick={onRetry}>Reintentar</Button></div>;

export function LeadInteractionsTab({ members, selectedMemberId, onChange, isLoading, isError, onRetry, interactions }: CommonProps & { interactions: LeadInteraction[] }) {
  return <Card className="p-5 sm:p-6"><CampaignContextSelector members={members} selectedMemberId={selectedMemberId} onChange={onChange} />{members.length === 0 ? <EmptyCampaign /> : isLoading ? <div className="space-y-3"><Skeleton className="h-20" /><Skeleton className="h-20" /></div> : isError ? <QueryError onRetry={onRetry} /> : interactions.length === 0 ? <p className="py-10 text-center text-muted-foreground">Todavía no se han registrado interacciones en esta campaña.</p> : <div className="relative space-y-6 before:absolute before:bottom-4 before:left-[18px] before:top-4 before:w-px before:bg-border">{interactions.map((interaction, index) => { const seller = personFullName(interaction.seller?.user) || interaction.created_by || "No especificado"; return <div key={interaction.id ?? index} className="relative flex gap-4"><div className="z-10 flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-primary/10 ring-4 ring-background"><MessageCircle className="h-4 w-4 text-primary" /></div><div className="min-w-0 flex-1 rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><Badge variant="outline">{displayEnum(interaction.type)}</Badge>{interaction.created_at && <time className="text-sm text-muted-foreground">{formatLeadDate(interaction.created_at, true)}</time>}</div><p className="mt-3 text-sm leading-6">{interaction.notes || "Sin notas"}</p><p className="mt-2 text-sm text-muted-foreground">Por: {seller}</p></div></div>; })}</div>}</Card>;
}

export function LeadTasksTab({ members, selectedMemberId, onChange, isLoading, isError, onRetry, tasks }: CommonProps & { tasks: LeadTask[] }) {
  return <Card className="p-5 sm:p-6"><CampaignContextSelector members={members} selectedMemberId={selectedMemberId} onChange={onChange} />{members.length === 0 ? <EmptyCampaign /> : isLoading ? <div className="space-y-3"><Skeleton className="h-24" /><Skeleton className="h-24" /></div> : isError ? <QueryError onRetry={onRetry} /> : tasks.length === 0 ? <p className="py-10 text-center text-muted-foreground">No hay tareas registradas para esta campaña.</p> : <div className="grid gap-4 md:grid-cols-2">{tasks.map((task, index) => <div key={task.id ?? index} className="rounded-xl border p-4"><div className="flex items-start gap-3">{task.is_done ? <CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-primary" /> : <Circle className="mt-0.5 h-5 w-5 shrink-0 text-muted-foreground" />}<div className="min-w-0 flex-1"><h3 className={`font-semibold ${task.is_done ? "text-muted-foreground line-through" : ""}`}>{task.title || "Tarea sin título"}</h3>{task.content && <p className="mt-2 text-sm leading-6 text-muted-foreground">{task.content}</p>}{task.due_date && <p className="mt-3 flex items-center gap-1.5 text-sm text-muted-foreground"><Clock3 className="h-4 w-4" />Vence: {formatLeadDate(task.due_date)}</p>}</div></div></div>)}</div>}</Card>;
}
